### ISSUE TITLE
Access denied due to unauthorized transaction

### ISSUE THREAD

**Issue by otnasusagus** [Midtrans/midtrans-python-client#10]
Saya mengalami error saat mencoba request token dengan error seperti ini:

MidtransAPIError at /shopping/token/
Midtrans API is returning API error. HTTP status code: `401`. API response: `{"error_messages":["Access denied due to unauthorized transaction, please check client or server key","Visit https://snap-docs.midtrans.com/#request-headers for more details"]}`

setelah saya lihat dokumentasinya katanya harus ditambahkan 3 header dibawah ini:
- Accept: application/json
- Content-Type: application/json
- Authorization: Basic AUTH_STRING

dan untuk menambahkan 3 header itu di bagian mananya kah?

**Comment by rizdaprasetya** [comment]
3 header tersebut sudah auto dihandle internally oleh Library ini.
Yg bisa menyebabkan error message tersebut adalah jika:
- Salah set server key,
- atau salah set isProduction

Pastikan keduanya sudah benar. Pastikan sudah buat akun untuk dapat server key:
https://docs.midtrans.com/en/welcome/preparation.html

isProduction set ke false untuk sandbox.

**Comment by otnasusagus** [comment]
terimakasih sarannya, saya rubah is_production = False dan tadi server key nya salah sekarang sudah bisa.
