### ISSUE TITLE
One or more merchant settings is invalid.

### ISSUE THREAD

**Issue by ahmadshiddiqn** [Midtrans/midtrans-python-client#25]
Saat mencoba Midtrans Sandbox untuk generate QR Code, error dengan response: 
```
{
    "status_code":"402",
    "status_message":"One or more merchant settings is invalid.",
    "id":"5e5c67fd-1639-4763-90c5-692df8e57509"
}
```

Dengan request:
```
core_api = midtransclient.CoreApi(
    is_production=True,
    server_key=f'{YOUR_SERVER_KEY}',
    client_key=f'{YOUR_CLIENT_KEY}'
)

param = {
    "payment_type": "qris",
    "transaction_details": {
        "gross_amount": 1,
        "order_id": "ID-Test-Trans-00001",
    },
    "qris": {
        "acquirer": "gopay"
    }
}
charge_response = core_api.charge(param)
print(charge_response)
```

Saya mengikuti param pada [contoh ini](https://api-docs.midtrans.com/#qris)

NB:
Dengan [contoh ini](https://github.com/Midtrans/midtrans-python-client/blob/master/examples/core_api/core_api_simple_example.py) saya sudah berhasil menggenerate QR Code. Saya sudah mengikuti arahan untuk menggunakan QRIS Simulator dan GoPay QR Simulator. Namun, hasilnya: "GoPay Payment failure" padahal  status masih pending, dan yang saya pilih adalah pilihan success. Pada status pembayaran di dashboard sanbox pun masih "pending"

![image](https://user-images.githubusercontent.com/45712248/169773061-1360bfd4-748d-4c02-ad03-a0b7f7825871.png)
![image](https://user-images.githubusercontent.com/45712248/169772460-fb2e6a9d-abaa-4987-85fe-53ff0e37354a.png)
![image](https://user-images.githubusercontent.com/45712248/169773149-c0df101f-f1c1-4a48-b823-77c5c685a088.png)

**Comment by Andrenzo17** [comment]
Hi @ahmadshiddiqn untuk akun sandboxnya sudah saya bantu sesuaikan, seharusnya sudah bisa melakukan pembayaran menggunakan QRIS simulator. Mohon di coba kembali ya.

Karena issuenya bersifat account-specific, untuk penyelesaian yang lebih personal & menjaga keamanan/privasi akun Anda, kami sarankan untuk melanjutkan menghubungi kami secara direct message melalui jalur kontak berikut: https://midtrans.com/id/contact-us/technical-integration-development/other-question

Note: karena Github issue tidak berhubungan langsung dengan Repo Github ini, maka issue akan di-close. Mohon melanjutkan kontak melalui jalur di atas. Silakan comment kembali jika ada kendala.

Terima kasih

**Comment by ahmadshiddiqn** [comment]
> Hi @ahmadshiddiqn
> 
> Issuenya dikarenakan akun sandboxnya saat dibuat gagal mendapat konfigurasi ID QRIS dengan sesuai. Untuk saat ini akun sandboxnya ID QRISnya sudah saya bantu re-generate, seharusnya sudah bisa coba buat transaksi QRIS kembali kemudian lakukan pembayaran menggunakan [QRIS simulator](https://simulator.sandbox.midtrans.com/qris/index). Mohon di coba kembali ya.
> 
> Karena issuenya bersifat account-specific, untuk penyelesaian yang lebih personal & menjaga keamanan/privasi akun Anda, kami sarankan untuk melanjutkan menghubungi kami secara direct message melalui jalur kontak berikut: https://midtrans.com/id/contact-us/technical-integration-development/other-question
> 
> Note: karena Github issue tidak berhubungan langsung dengan Repo Github ini, maka issue akan di-close. Mohon melanjutkan kontak melalui jalur di atas. Silakan comment kembali jika ada kendala.
> 
> Terima kasih

Baik, terima kasih atas jawabannya @Andrenzo17 . Saya akan coba kembali QRIS Simulatornya, dan jika ada kendala di luar repo akan saya tanyakan melalui kanal yg sudah disediakan di atas.
