### ISSUE TITLE
No MID/TID saat charge Credit Card

### ISSUE THREAD

**Issue by irfanpule** [Midtrans/midtrans-python-client#5]
saya mencoba untuk menggunakan metode pembayaran `credit card` dari contoh yang sudah disediakan [disini](https://github.com/Midtrans/midtrans-python-client/blob/master/examples/core_api/core_api_credit_card_example.py) tapi mendapati error seperti ini
```
Midtrans API is returning API error. API status code: `402`. API response: `{"status_code":"402","status_message":"No MID/TID for this transaction","id":"7415f081-638c-4b0a-bd84-265e2ec369b5"}`
```

**Comment by rizdaprasetya** [comment]
Mungkin karena akunnya untuk credit card sudah temprorary deactive karena sudah lama, silahkan coba lagi, akunnya sudah di reactivate @irfanpule

**Comment by irfanpule** [comment]
ok trims, sudah bisa

**Comment by mistraminayasa** [comment]
> ok trims, sudah bisa

Itu bisa laginya caranya gimana? saya juga dapet issue yang sama.

**Comment by irfanpule** [comment]
di reactive sama pihak midtransnya.

**Comment by rizdaprasetya** [comment]
Jika merchant ID sandbox Anda masih ada yg mendpat issue tersebut, silahkan kontak by email ke support[at]midtrans.com ya. terima kasih
