### ISSUE TITLE
memasukkan response_dict MidtransAPIError 

### ISSUE THREAD

**Issue by irfanpule** [Midtrans/midtrans-python-client#6]
saya agak kesulisan untuk meneruskan informasi `Error` ketika melakukan `try` `except` pada class `MidtransAPIError` karena data yang diperoleh adalah `string`.

Agar saya memperoleh raw data, mungkin `response_dict` [http_client.py line 53](https://github.com/Midtrans/midtrans-python-client/blob/master/midtransclient/http_client.py#L53) bisa dimasukkan ke `MidtransAPIError`.

Mungkin bisa jadi seperti ini 
```python
class MidtransAPIError(Exception):
    def __init__(self, message, response_dict=None):
        self.message = message
        self.response_dict = response_dict
```

```python
raise MidtransAPIError(
    'Midtrans API is returning API error. API status code:'
    ' `{0}`. API response: `{1}`'.format(response_dict['status_code'], response_object.text), 
    response_dict=response_dict
)
```

Hal ini bisa jadi peningkatan berarti bagi saya. Terima kasih.

**Comment by rizdaprasetya** [comment]
Good idea! @irfanpule 
Sudah ditambahkan disini ya: 
https://github.com/Midtrans/midtrans-python-client/pull/7
Updated to latest version: `v1.1`
Thanks

**Comment by irfanpule** [comment]
Terima kasih
