### ISSUE TITLE
nanya snap

### ISSUE THREAD

**Issue by kwhandy** [Midtrans/midtrans-python-client#9]
Hi! itu yang dokumentasi flask_app instruksinya cuma gitu aja? run di local kok simple checkout nya ga bisa?

**Comment by rizdaprasetya** [comment]
Hi @kwhandy silahkan didetailkan maksudnya `ga bisa` ini seperti apa? ada error message? Untuk issue teknis sebaiknya provide evidence.

**Comment by kwhandy** [comment]
saya run flask_app nya via localhost tapi pas saya arahin simple checkout dan saya klik checkout buttonnya ga terjadi apa2 dan saya buka console chrome muncul eror "../snap/snap.js net::ERR_BLOCKED_BY_CLIENT"

**Comment by rizdaprasetya** [comment]
Hi @kwhandy biasanya `net::ERR_BLOCKED_BY_CLIENT` karena browser extensionnya ada yg block external javascript resource. Silahkan coba pakai incognito mode. atau browser lain tanpa extension

**Comment by kwhandy** [comment]
Works! makasih

**Comment by rizdaprasetya** [comment]
Thanks for confirming @kwhandy 
Kalo ada info kira kira extension apa yg ngeblock boleh diinfokan ke sini, biar kita cek atau antisipasi.
